# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’

target 'Test' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test

pod ‘Alamofire’

  target 'TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
